---
title: "lab9extra_jelia"
author: "James Elia"
date: "11/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- runif(1, 0, 10)  
if(x > 3) {
        y <- 10
} else {
        y <- 0}
for(i in 1:10) {
        print(i)
}
x <- c("f", "a", "c", "e")
for(i in 1:4) {
        print(x[i])  
}
for(i in seq_along(x)) {   
        print(x[i])
}
for(letter in x) {
        print(letter)
}
for(i in 1:4) print(x[i])
x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) { 
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)
f <- function() {
}
class(f)  
f()   
```

```{r}
f <- function() {
        cat("Hello, Jeff!\n")
}
f()
f <- function(num) {
        for(i in seq_len(num)) {
                cat("Hello, class!\n")
        }
}
f(3)
f <- function(num) {
        hello <- "Hello, people!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(3)
print(meaningoflife)
f <- function(num = 1) {
        hello <- "Hello, stranger!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()  
f(2)
f(num = 2)
```

